In [1]:
import numpy as np
np.set_printoptions(precision=1)

In [12]:
# m2dgr
Trans_lidar_imu_origin = np.array([[1, 0, 0], 
                                   [0, 1, 0], 
                                   [0, 0, 1,]])
imu_tran_R = np.array([ [1,0,0],
                        [0,-1,0], 
                        [0,0,-1]])
# For NED type IMUs, the orientation of the world frame is x-north, y-east, z-down, relative to magnetic north.
print("imu_tran_R @ Trans_lidar_imu_origin", imu_tran_R @ Trans_lidar_imu_origin)
print("Trans_lidar_imu_origin @ imu_tran_R", Trans_lidar_imu_origin @ imu_tran_R)

imu_tran_R @ Trans_lidar_imu_origin [[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
Trans_lidar_imu_origin @ imu_tran_R [[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]


In [39]:
# camera m2dgr
Trans_lidar_imu_origin = np.array([[0.,  0., 1.],
                                   [-1,  0., 0.,],
                                   [0.,  -1, 0]])
# imu_tran_R = np.array([ [0, -1, 0],
#                         [0, 0, 1],
#                         [-1, 0, 0]])
# imu_tran_R = np.array([ [0, 1, 0],
#                         [0, 0, 1],
#                         [1, 0, 0]])
# imu_tran_R = np.array([ [0, 0, 1],
#                         [1, 0, 0],
#                         [0, 1, 0]])
ENU =  np.array([[ 0, -1, 0],
                  [ 1,  0, 0],
                  [ 0,  0, 1]])
# imu_tran_R = np.array([ [0, 0, 0],
#                         [0, 0, 1],
#                         [0, 1, 0]])
# For NED type IMUs, the orientation of the world frame is x-north, y-east, z-down, relative to magnetic north.
# [[ 1  0  0]
#  [ 0 -1  0]
#  [ 0  0 -1]]
#  ENU
# [[ 0 -1 0]
#  [ 1  0 0]
#  [ 0  0 1]]
# print("Trans_lidar_imu_origin\n", Trans_lidar_imu_origin)
print("imu_tran_R @ Trans_lidar_imu_origin\n", np.linalg.inv(ENU) @ Trans_lidar_imu_origin)
print("imu_tran_R @ Trans_lidar_imu_origin\n", Trans_lidar_imu_origin @ np.linalg.inv(ENU))
# print("imu_tran_R @ Trans_lidar_imu_origin\n", np.linalg.inv(Trans_lidar_imu_origin) @ ENU)
# print("imu_tran_R @ Trans_lidar_imu_origin\n", ENU @ np.linalg.inv(Trans_lidar_imu_origin))
imu_tran_R =  np.linalg.inv(Trans_lidar_imu_origin) @ ENU
print("imu_tran_R\n", imu_tran_R)
print("inv\n", np.linalg.inv(Trans_lidar_imu_origin))

# print("np.linalg.inv(Trans_lidar_imu_origin)", np.linalg.inv(Trans_lidar_imu_origin))
# print("imu_tran_R @ Trans_lidar_imu_origin", imu_tran_R @ np.linalg.inv(Trans_lidar_imu_origin))
# print("Trans_lidar_imu_origin @ imu_tran_R", np.linalg.inv(Trans_lidar_imu_origin) @ imu_tran_R)

imu_tran_R @ Trans_lidar_imu_origin
 [[-1.  0.  0.]
 [ 0.  0. -1.]
 [ 0. -1.  0.]]
imu_tran_R @ Trans_lidar_imu_origin
 [[ 0.  0.  1.]
 [ 0. -1.  0.]
 [ 1.  0.  0.]]
imu_tran_R
 [[-1.  0.  0.]
 [ 0.  0. -1.]
 [ 0. -1.  0.]]
inv
 [[-0. -1. -0.]
 [-0. -0. -1.]
 [ 1.  0.  0.]]


In [44]:
# # newer college
# Trans_lidar_imu_origin = np.array([[-1, 0, 0],
#                                    [0, -1, 0],
#                                    [0, 0, 1]])
# imu_tran_R = np.array([ [0, -1,0],
#                         [1,0,0],
#                         [0,0,1]])
# theta_x = 0
# theta_y = 0
# theta_z = 0
# def rot_x(theta):
#     return np.array([ [np.cos(theta), -np.sin(theta), 0],
#                     [np.sin(theta), np.cos(theta), 0],
#                     [            0,             0, 1]])
# def rot_y(theta):
#     return np.array([ [np.cos(theta), 0, -np.sin(theta)],
#                       [            0, 1,              0],
#                       [np.sin(theta), 0, np.cos(theta)]]) 
# def rot_z(theta):
#     return np.array([ [ 1,             0,             0],
#                       [ 0, np.cos(theta),-np.sin(theta)],
#                       [ 0, np.sin(theta), np.cos(theta)]])

# for x_i in range(0, 4):
#     for y_i in range(0, 4):
#         for z_i in range(0, 4):
#             theta_x = 0
#             theta_y = 0
#             theta_z = 0
#             theta_x = theta_x + x_i * 90
#             theta_y = theta_y + y_i * 90
#             theta_z = theta_z+ z_i * 90
#             rad_x = np.deg2rad(theta_x)
#             rad_y = np.deg2rad(theta_y)
#             rad_z = np.deg2rad(theta_z)
            
#             print(x_i, y_i, z_i)
#             print(theta_x, theta_y, theta_z)
#             # print(rad_x, rad_y, rad_z)
#             print(rot_x(rad_x) @ rot_y(rad_y) @rot_z(rad_z) @imu_tran_R)



# print("imu_tran_R\n", imu_tran_R)
# B_inv_A = imu_tran_R @ np.linalg.inv(Trans_lidar_imu_origin)
# A_B_inv_A = Trans_lidar_imu_origin @ imu_tran_R @ np.linalg.inv(Trans_lidar_imu_origin)
# print("B_inv_A\n", B_inv_A)
# print("A_B_inv_A\n", A_B_inv_A)

In [50]:
# newer college
Trans_lidar_imu_origin = np.array([[-1, 0, 0],
                                   [0, -1, 0],
                                   [0, 0, 1]])
imu_tran_R = np.array([[ -1,  0,   0],
                         [ 0, -1,   0],
                         [ 0,  0,  -1]])
imu_tran_R @ np.linalg.inv(Trans_lidar_imu_origin)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0., -1.]])

In [43]:
# urbanNav
Trans_lidar_imu_origin = np.array([[1, 0, 0],
                                   [0, 1, 0],
                                   [0, 0, 1,]])
imu_tran_R = np.array([ [0, 1, 0,],
                        [1, 0, 0], 
                        [0, 0, -1]])
imu_tran_R @ Trans_lidar_imu_origin
# For ENU type IMUs, the orientation of the world frame is x-east, y-north, z-up, relative to magnetic north.

array([[ 0,  1,  0],
       [ 1,  0,  0],
       [ 0,  0, -1]])